### ISSUE TITLE
fails to switch monster

### ISSUE THREAD

**Issue by jasonh54** [jasonh54/battlebot#116]
can switch from monster 1 to monster 2 but fails to switch from monster 2 to monster 1
can switch from low index monster in the arraylist to a high index monster in the arraylist but not vice versa
monster 1 -> monster 6 is allowed
fails to switch from monster 6 to monster 3 (or any monster before number 6

**Comment by MutantPiggieGolem1** [comment]
fixed

**Comment by jasonh54** [comment]
issue has been fixed
